version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: database_container
    hostname: mysql
    command: >
          mysqld
            --character-set-server=utf8
            --collation-server=utf8_unicode_ci
            --skip-character-set-client-handshake
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=root"
